trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'testheroku:$(build.buildId)'

steps:
- script: dotnet restore
- script: dotnet build
- script: cd ./TestHeroku && heroku container:push web --app testherokucorerpt --context-path ..
  displayName: 'docker build'
