trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'testheroku:$(build.buildId)'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'
- script: dotnet build
  displayName: 'dotnet build'
- script: cd ./TestHeroku && heroku login && heroku container:push web --app testherokucorerpt --context-path ..
  displayName: 'push image to Heroku'
